# Generated by Django 3.2.20 on 2023-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=1, verbose_name='性别')),
                ('class_null', models.CharField(max_length=5, verbose_name='班级编号')),
            ],
            options={
                'db_table': 'to_student',
            },
        ),
    ]
