# Generated by Django 3.2.8 on 2023-09-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_demo', '0002_author_book_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='drf_demo.author', verbose_name='作者'),
            preserve_default=False,
        ),
    ]
