# Generated by Django 3.2.8 on 2023-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_demo', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='drf_demo.Author', verbose_name='作者'),
        ),
    ]
